### ISSUE TITLE
Transitive dependencies aren't built with swc_transpiler

### ISSUE THREAD

**Issue by Nick-Mazuk** [aspect-build/rules_swc#25]
Let's say I have 3 packages where:

- `package-a` depends on `package-b`
- `package-b` depends on `package-c`
- `package-c` has no dependencies

And each of these are defined with `swc_transpiler`, for instance:

```bazel
swc_transpiler(
    name = 'package-a',
    srcs = ['index.ts'],
    data = [
        "//package-b",
    ],
    visibility = ["//visibility:public"],
)
```

Running…

```bash
bazel build //package-a
```

…will not build `package-c`.

Here's a minimal reproduction: https://github.com/Nick-Mazuk/bazel-swc-deps

**Comment by alexeagle** [comment]
That's not actually the bug, there's no reason that the default output of package-a (the .js files) would require that bazel build package-b or package-c. Bazel only does the minimal work required to produce the outputs you request.

However, the issue you posted in slack was that a program which depends on A shouldn't be forced to declare dependencies on B or C in order to get those .js files in its runfiles tree.
