### ISSUE TITLE
swcrc must be in source package 

### ISSUE THREAD

**Issue by joeljeske** [aspect-build/rules_swc#42]
Currently, the swcrc must be in the source package and fails on the copy_to_bin_action step if it exists in a separate package. 

Workaround is to make sure the swcrc is a generated file instead of a source file.

**Comment by alexeagle** [comment]
The latest aspect_bazel_lib should suggest a copy_to_bin rule, which fixes the developer experience for this I think

**Comment by joeljeske** [comment]
I want to allow the swcrc to be in a separate (parent) package, and I don't want to have to copy it into current package even with the suggestions. 

If SWC allows the config to be in a different directory, why should rules_swc care?

**Comment by alexeagle** [comment]
As you know, rules_js runs node programs with the bazel-out folder as the working directory. All inputs are read from there, since it's a single source tree where the node_modules exist as well.

It's a Bazel restriction that outputs must be created by the package that contains the input files. In order to write .swcrc to the bazel-out folder, the `copy_to_bin` has to be in the package containing .swcrc.

**Comment by joeljeske** [comment]
Ah so sorry. I didn't realize this was a constraint of all being auto generated. It had not occurred to me. So sorry. 
 

It does make me wonder, is there value in allowing source artifacts in an action ever?

**Comment by alexeagle** [comment]
We copy sources to the output folder automatically but only when they are in the current Bazel package. Otherwise it needs copy_to_bin
