### ISSUE TITLE
Run bare rust CLI binary, no node

### ISSUE THREAD

**Issue by alexeagle** [aspect-build/rules_swc#88]
It's slow to start a NodeJS process for every spawn of swc, and it's extra weight to send to remote execution service.

SWC has a binary codenamed "swcx" which is the bare Rust binary without the node binding. This should be suitable for use in Bazel.

https://github.com/aspect-build/rules_swc/pull/57 has some longstanding WIP for this, but it needs a sponsor to fund the rest of the work.

**Comment by alexeagle** [comment]
#57 has landed, thanks @realtimetodie

**Comment by binoche9** [comment]
Hi, I noticed that this changed [removed](https://github.com/aspect-build/rules_swc/commit/6358e06ac2a8d6aca2c2ea0cd6ea9dc7b9217a27#diff-35f2e434ca5489813771ec0fe2fa53eea84330e6a4995cd3e33efe85154d1f99L45-L51) the `@aspect_rules_swc//swc:cli` target even though it's still referenced in the [documentation for using rules_swc in a custom rule](https://docs.aspect.build/rules/aspect_rules_swc/#in-a-custom-rule)

Is using rules_swc in a custom rule no longer supported, or is there some other cli tool exposed through rules_swc that I can use for a custom `ctx.actions.run()`?

**Comment by realtimetodie** [comment]
@binoche9 I'm sorry. This is only a documentation error. The Bazel target was renamed to -> `@aspect_rules_swc//swc:swc_compile`.

https://github.com/aspect-build/rules_swc/blob/ee7ca0247036509464d70b1d396ddd884c2d8bf1/swc/defs.bzl#L18-L20

The reason is, that the Bazel rule implementation only uses the `compile` command of the SWC cli. I think this is more sound.

In the future, there will also be a Bazel `@aspect_rules_swc//swc:swc_bundle` target and a Bazel `@aspect_rules_swc//swc:swc_minify` target, but these features are not yet implemented in the Rust-based SWC cli.

https://github.com/swc-project/swc/blob/61397267bbd672fabd83baba0f9980e3d1d84ccf/bindings/swc_cli/src/commands/bundle.rs#L10

https://github.com/swc-project/swc/blob/61397267bbd672fabd83baba0f9980e3d1d84ccf/bindings/swc_cli/src/commands/minify.rs#L10

**Comment by realtimetodie** [comment]
@binoche9 Please let me know if this works for you 👍.

**Comment by binoche9** [comment]
Yeah I believe that should give me enough to work with for now. Thanks for the quick response!

**Comment by alexeagle** [comment]
reopened since I think the doc fix wasn't right.

**Comment by binoche9** [comment]
Actually I'm still seeing `no such target '@aspect_rules_swc//swc:swc_compile': target 'swc_compile' not declared in package 'swc'` - it seems that [`swc_compile`](https://github.com/aspect-build/rules_swc/blob/03b5ce0dddc8b06027d38d88042274659954fded/swc/defs.bzl#L19) (in `swc/defs.bzl`) isn't exposed in [`swc/BUILD.bazel`](https://github.com/aspect-build/rules_swc/blob/03b5ce0dddc8b06027d38d88042274659954fded/swc/BUILD.bazel)?

**Comment by alexeagle** [comment]
`swc_compile` is a rule, not a binary target. 
Like the doc says "mimic swc/private/swc.bzl" - so you were right earlier, you need to lookup the swc toolchain and then get the `swcinfo.swc_binary` which will be a binary target in some external repo for the resolved platform.
https://github.com/aspect-build/rules_swc/blob/main/swc/private/swc.bzl#L202-L212

It does look like we should maybe expose the `_swc_action` function in the `swc` struct declared at the end of that file.
